name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      # Không chạy test, không chạy mocha, không docker exec gì hết

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build   # chỉ deploy khi build ok

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build images for deployment
        run: docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Push images to Docker Hub
        run: |
          docker tag 22728851-hieucd61745-eproject-auth:latest hieucd61745/22728851_hieucd61745_eproject:auth-latest
          docker push hieucd61745/22728851_hieucd61745_eproject:auth-latest

          docker tag 22728851-hieucd61745-eproject-product:latest hieucd61745/22728851_hieucd61745_eproject:product-latest
          docker push hieucd61745/22728851_hieucd61745_eproject:product-latest

          docker tag 22728851-hieucd61745-eproject-order:latest hieucd61745/22728851_hieucd61745_eproject:order-latest
          docker push hieucd61745/22728851_hieucd61745_eproject:order-latest

          docker tag 22728851-hieucd61745-eproject-api-gateway:latest hieucd61745/22728851_hieucd61745_eproject:api-gateway-latest
          docker push hieucd61745/22728851_hieucd61745_eproject:api-gateway-latest
