name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build  # chá»‰ deploy khi build ok

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build images for deployment
        run: docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Tag & Push images to Docker Hub
        run: |
          # AUTH
          docker tag eproject-phase-1-auth:latest hieucd61745/auth:latest
          docker push hieucd61745/auth:latest

          # PRODUCT
          docker tag eproject-phase-1-product:latest hieucd61745/product:latest
          docker push hieucd61745/product:latest

          # ORDER
          docker tag eproject-phase-1-order:latest hieucd61745/order:latest
          docker push hieucd61745/order:latest

          # API-GATEWAY
          docker tag eproject-phase-1-api-gateway:latest hieucd61745/api-gateway:latest
          docker push hieucd61745/api-gateway:latest